### PR TITLE
Bug 1638784 - Create WiFi directories on startup

### PR DESCRIPTION
**Pull request by lissyx**

### CODE REVIEW

**Comment by jackdesu** [comment]
Since we have branched device_generic_goldfish [1], why don't we make it adapt B2G emulator?

also, I am trying more rc configuration as below, will update soon.
```
service wpa_supplicant /vendor/bin/hw/wpa_supplicant -Dnl80211 -iwlan0 -c/vendor/etc/wifi/wpa_supplicant.conf -g@android:wpa_wlan0
socket wpa_wlan0 dgram 660 wifi wifi
group system wifi inet
oneshot
disabled
```
[1]: https://github.com/kaiostech/device_generic_goldfish/blob/gonk_android-10.0.0_r11/init.ranchu.rc#L24

**Comment by lissyx** [comment]
> Since we have branched device_generic_goldfish [1](https://github.com/kaiostech/device_generic_goldfish/blob/gonk_android-10.0.0_r11/init.ranchu.rc#L24), why don't we make it adapt B2G emulator?

I did the PR before, as I said on Matrix, happy to change to something similar to on-device and trigger on post-fs-data instead of zygote-start

**Comment by lissyx** [comment]
> also, I am trying more rc configuration as below, will update soon.

What do you want to try? The issue blocking `wpa_supplicant` is pretty clear:
```
05-15 20:04:11.605  1695  1881 D SupplicantStaManager: SupplicantCallback.onInterfaceRemoved(): wlan0
05-15 20:04:11.605  2313  2313 E /vendor/bin/hw/wpa_supplicant: android::WriteStringToFile open failed: No such file or directory
05-15 20:04:11.605  2313  2313 E wpa_supplicant: Failed to write to /data/vendor/wifi/wpa/wpa_supplicant.conf. Errno: No such file or directory
05-15 20:04:11.605  2313  2313 E wpa_supplicant: Failed copying /vendor/etc/wifi/wpa_supplicant.conf to /data/vendor/wifi/wpa/wpa_supplicant.conf.
05-15 20:04:11.605  2313  2313 E wpa_supplicant: Conf file does not exists: /data/vendor/wifi/wpa/wpa_supplicant.conf
05-15 20:04:11.606  1695  1940 E WifiNative: Failed to setup iface in supplicant
05-15 20:04:11.606  1695  1940 D WifiNative: command result: id=1, status=1
```

As stated in the bug, this is just because on ranchu emulator, it populates those directories on `zygote-start` event, while on device the very same code is triggered but on `post-fs-data`.

**Comment by jackdesu** [comment]
We are guessing wether it relate to the arguments we used to start wpa_supplicant in rc.
However, I am suffering from unstable B2G emulator and it slow down our progress.

Yes, it is quite clear that device complain some directories are missed.
Let's fix this and we will do more study later.

**Comment by lissyx** [comment]
> We are guessing wether it relate to the arguments we used to start wpa_supplicant in rc.

Your suggested change to the service parameter would still make use of `/data/vendor/wifi/wpa/` that is the missing directory



>  However, I am suffering from unstable B2G emulator and it slow down our progress.

You should be able to build and run x86_64 with all my (pending) patches, are you referring to ARM emulator?

**Comment by lissyx** [comment]
https://github.com/kaiostech/device_generic_goldfish/pull/2

**Pull request closed without merging**
